{{- include "cloudflare-prometheus-exporter.validateValues" . }}
{{- if not .Values.cloudflare.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-prometheus-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflare-prometheus-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.cloudflare.existingSecretKey }}: {{ required "cloudflare.apiToken is required when cloudflare.existingSecret is not set" .Values.cloudflare.apiToken | quote }}
{{- end }}
{{- if and .Values.basicAuth.enabled (not .Values.basicAuth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-basic-auth" (include "cloudflare-prometheus-exporter.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflare-prometheus-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.basicAuth.existingSecretUsernameKey }}: {{ required "basicAuth.username is required" .Values.basicAuth.username | quote }}
  {{ .Values.basicAuth.existingSecretPasswordKey }}: {{ required "basicAuth.password is required" .Values.basicAuth.password | quote }}
{{- end }}
